export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  BOOK_NOT_FOUND: 'BOOK_NOT_FOUND',
  BOOK_ISBN_TAKEN: 'BOOK_ISBN_TAKEN',
  BOOK_COPIES_INVALID: 'BOOK_COPIES_INVALID',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
